services:
  - type: web
    name: howsgol-tsag-burtgel
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SUPERADMIN_USER
        value: admin123
      - key: SUPERADMIN_PASS
        value: "123123"
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        value: howsgol-ai_2026
      - key: GROQ_API_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://howsgol-tsag-burtgel.onrender.com
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: DEFAULT_COMPANY_NAME
        value: bayr
      - key: DEFAULT_COMPANY_PHONE
        value: "12345678"
      - key: DEFAULT_COMPANY_USERNAME
        value: bayr
      - key: DEFAULT_COMPANY_PASSWORD
        value: "12345678"
      - key: DEFAULT_COMPANY_PAGE_LINK
        value: https://www.facebook.com/search/top?q=nowijufaqae
      - key: DEFAULT_COMPANY_INFO_PHONE
        value: "12345677"
      - key: DEFAULT_COMPANY_LOCATION_LINK
        value: https://maps.app.goo.gl/tppoPZmyL4IMq29EFG
      - key: DEFAULT_COMPANY_WEBSITE_LINK
        value: https://howsgol-tsag-burtgel.onrender.com/bayr
